export enum DeviceType {
    MOBILE_SMARTPHONES = 'MOBILE_SMARTPHONES',
    LAPTOP_NOTEBOOKS = 'LAPTOP_NOTEBOOKS',
    AUDIO_EQUIPMENT = 'AUDIO_EQUIPMENT',
    SMART_HOME_DEVICES = 'SMART_HOME_DEVICES',
    CAMERA = 'CAMERA',
    GAMING_CONSOLES = 'GAMING_CONSOLES'
}
